services:
  - type: web
    name: shopease-app
    env: node
    plan: starter
    buildCommand: |
      cd frontend && npm install && npm run build &&
      cd ../backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shopease-db
          property: connectionString
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: JWT_SECRET
        generateValue: true
    domains:
      - shopease-app.onrender.com

databases:
  - name: shopease-db
    plan: starter